### ISSUE TITLE
location issues

### ISSUE THREAD

**Issue by crazyhuggins** [JazzleWare/jazzle-parser#7] opened 2016-11-28 12:07 UTC
@icefapper Hi! I tried this module. Awsome work!

But is there any way I can turn of this misleading location stuff ? In Acorn and Esprima that is off by default, and can be activated through options.

And I also noticed that the location is not compatible with either Acorn or Esprima. Is this something that will be fixed?

**Comment by icefapper** [comment] 2016-11-28 20:19
@crazyhuggins Hi, and thanks for using my brainkid!

> But is there any way I can turn of this misleading location stuff ? In Acorn and Esprima that is off by default, and can be activated through options.

I would be more than glad to make location tracking optional, but as the location tracker subsystem is (slightly) "rooted" in the code, so to speak, making it optional demands a couple days, and I'm so short of time I'm begging for seconds; I've actually been considering making it optional for some time though, and I'd be more than glad to give you push access and/or accept PRs if you believe you could help me do it sooner than I singly can!

> And I also noticed that the location is not compatible with either Acorn or Esprima. Is this something that will be fixed?

There are some case (like marking the start and the end of a `TemplateElement` in a template literal, or a `LetDeclaration` in a for statement) where jazzle intentionally deviates from esprima, but I never thought there might be a case where it is incompatible with acorn. *sigh*

But that I hear the location tracker is acting buggy is a serious issue. 

Could I ask you provide me with more detail on the case you are finding to be incompatible with other parsers, namely Acorn and Esprima? The code fragment maybe?

**Comment by crazyhuggins** [comment] 2016-11-28 22:50
@icefapper Give me to the end of this day, and I will finish reading your code and can provide more accurate infromation about things. And I also noticed that not all ES2016 aren't supported yet, and so is es2017.  

Regarding the location, I will have to study your code now before I can look into it and perhaps find a solution for turning it off.

Btw. Is this module 100% ESTree compatible? 

For code fragments. Yep. You will get that by the end of my day. Approx within 12 - 13 hours.

**Comment by crazyhuggins** [comment] 2016-11-29 03:57
@icefapper I can help you out with this module. No problem. Just now I am reading and studing the code.
However. This combos are failing for me on the master branch. Could you fix this asap?

### Comments
```js
// Hello, world!\n42

// line comment
42
// Hello, world!

// Hello, world!

//   Another hello
42

if (x) { doThat() // Some comment
 }

if (x) { // Some comment
doThat(); }

/* block comment */--> comment

--> comments

<!-- comment

<!-- comment

<!-- foo
``` 

### Other combos
```js
try {} catch ([a,a]) {}
var [let] = answer;
try { } catch ([a] = []) { }
for (let {x: y = let};;) {}
class A {a(eval){}}
export {default} from "foo";
export {foo as default} from "foo";
export {foo as bar} from "foo";
export {foo as default, bar} from "foo";
export {foo} from "foo";
export {foo, bar} from "foo";
export {foo as default};
export {foo as bar};
export {};
export {foo};
export {foo, bar,};
export {foo, bar};
for (x of let) {}
`.14
02
09.5
arguments++
++eval
++arguments
delete x
eval = 42
arguments = 42

```

**Comment by crazyhuggins** [comment] 2016-11-29 04:10
And also this one fails in the master branch

```js
function eval() { }
function arguments() { }
function test(t, t) { }
(function test(t, t) { })
function eval() { function inner() { "use strict" } }
var hi = function eval() { };
var hi = function arguments() { };
```

**Comment by icefapper** [comment] 2016-11-29 09:57
@crazyhuggins I just can't thank you enough for the time and effort you have put helping me crush jazzle's bugs.
> I can help you out with this module. No problem. Just now I am reading and studing the code.

That would be great! By the way, since I've not put enough time in commenting the code, please feel free to ask about any part of it that looks confusing to you.

Now for the cases that are causing the parser croak:

* `try {} catch ([a,a]) {}`
   Per https://www.ecma-international.org/ecma-262/7.0/index.html#sec-try-statement-static-semantics-early-errors, it is indeed a syntax error -- an early error to be precise.
   Esprima catches this error properly, but looks like Acorn, as of version 4.0.0, won't complain.

* `for (let {x: y = let};;) {}`
    This is an actual syntax error too -- Declarators other than a plain Identifier _must_ be followed by an initializer (unless they are the left-hand-side of a for-in/for-of); in this case, for example, we have a declarator `{ x: y = let }`, which is not an Identifier, and is not followed by an initializer; a possible correction could be `for (let {x: y = let} = 12;;) {}`

* `try { } catch ([a] = []) { }`
  This is also a syntax error -- [catch parameters can not have initializers](https://www.ecma-international.org/ecma-262/7.0/index.html#prod-CatchParameter)

* `var [let] = answer;`
  `class A {a(eval){}}`
  These are actually valid programs and should parse correctly in jazzle; I've pushed an updated version of jazzle to the master branch, and I have managed to parse the two programs above without any issues. Could I ask you check the above two examples with using the master branch and tell me if you are still getting errors? That would be great!

As for the examples below:
```js
.14 // always valid
02
09.5
arguments++
++eval
++arguments
delete x
eval = 42
arguments = 42

function eval() { }
function arguments() { }
function test(t, t) { }
(function test(t, t) { })
function eval() { function inner() { "use strict" } }
var hi = function eval() { };
var hi = function arguments() { };
```
They are all valid programs when **not** in strict mode. In the strict mode though, all will be invalid programs, except for the first one, namely `.14`, which is valid in both strict and non-strict mode. Again, they are all parsing correctly on my machine, but I'd be very glad if you could tell me you are having issues with any of them :)
  
Also regarding the programs below,
```js
export {default} from "foo";
export {foo as default} from "foo";
export {foo as bar} from "foo";
export {foo as default, bar} from "foo";
export {foo} from "foo";
export {foo, bar} from "foo";
export {foo as default};
export {foo as bar};
export {};
export {foo};
export {foo, bar,};
export {foo, bar};
```
I guess I know the reason you are encountering issues parsing them.
Theses are all **module-level source elements**, which means they have to be parsed as modules, rather than scripts.

But jazzle, if not told what mode to parse a piece of code in, will parse any given piece of code in script mode, rather than in module mode; in order to tell jazzle to parse a piece of code as a module (rather than a script), pass `true` as the second argument to `Parser` constructor:

```js
var code = 'export {default} from "foo"';
var Parser = require('jazzle').Parser;

// will parse it as a script, which will raise an error,
// because `export` is a module-specific program element
new Parser(code).parseProgram();
```
But,
```js
// will parse it as a module, with absolutely no errors
new  Parser(code, true).parseProgram()
```


Finally, 
```js
// Hello, world!\n42

// line comment
42
// Hello, world!

// Hello, world!

//   Another hello
42

if (x) { doThat() // Some comment
 }

if (x) { // Some comment
doThat(); }

/* block comment */--> comment

--> comments

<!-- comment

<!-- comment

<!-- foo
```

This code is parsing properly for me; could I ask you what is your exact problem with it? I mean, are you having any issues with the comment tracking (which is not implemented yet), or is it anything else I'm missing?

Thanks a lot reading this far.

I can't await your feedback!

**Comment by icefapper** [comment] 2016-11-29 10:33
> But to get things right, you are mixing range and location, right? So what is inside your "loc" object, is the location, and your start, stop is the range? So both have to have a switch to turn them on and off?

Sorry I totally missed this comment. Your assumptions are totally correct.

in jazzle, like acorn, the `start` and `end` attributes of every node signify the start and end offset of the node in the source code, or its "range", as you said. These attributes are always present, with no option to switch it off in neither Jazzle nor acorn.

it would be great to know if you have any suggestions about improving/changing how location tracking works.

Also, for the record, Jazzle is 100% ESTree compatible, or at least as far as I know; please do not hesistate to tell if you find any compatibility issues between Jazzle and ESTree, though!

**Comment by crazyhuggins** [comment] 2016-11-29 11:04
@icefapper  Hi. I am still reading through your source code, and yes I see now you are right about the  combinations. 

Me too prefer Acorn over Esprima, and it's positive that this module is 100% ESTree compatible. However you are missing the Position and SourceLocation prototypes mentioned in the specs. See Acorn:
https://github.com/ternjs/acorn/blob/master/src/locutil.js

`start` and `end` are wrapped inside an `range` object in Acorn, equal to `loc` for location.  And both this is turned off by default. However in Acorn you can do this to activate them.

```js
acorn.parse('1', { location: true, range: true });
```
So to implement this is very easy and shouldn't take you more then 30 minutes to implement.

Take this as one example: https://github.com/JazzleWare/jazzle-parser/blob/master/src/class%40Parser.js#L60-L61

You take out end and start from here, and put them into an range object.

This would do the trick for every returned `elem` object.

```js
// this is nothing if options is not set
var range;
if(options.range) {
range = {
start: startcStatic, 
end: cStatic
} 
}
 elem = this.parseMeth( { type: 'Identifier', name: 'static', range, raw: rawStatic,
                                  loc: { start: startLocStatic, end: { line: liStatic, column: colStatic } }}   , CLASS_MEM);
```
You do similar for location.

This however require that you in the `Parser`, change the boolean arg to an option object. Also here you can "copy" from Acorn. 

```js
new  Parser(code, {
sourceType: 'module'
location: true,
range. true,
}).parseProgram()
```

Hope I gave you a few ideas? I am still reading the source code so will finish that now.

**Comment by icefapper** [comment] 2016-11-29 12:00
Thank you for the hints!
As for the ranges options in acorn, I guess you have missed the point -- it will not "replace" `start` and `end` with `range`; it adds it alongside them, as illustrated in https://runkit.com/583d655282382300136be92c/583d678b82382300136be9fd

I would be glad to further know you opinions about it.

> This however require that you in the Parser, change the boolean arg to an option object. Also here you can "copy" from Acorn.
 
You are completely right. I have to turn it into an option as soon as possible.

**Comment by crazyhuggins** [comment] 2016-11-29 12:15
@icefapper Can you try this combination - both strict and not strict and let me know ASAP if it works for you?

```js
if (morning) function a(){}
```

I will come back with a comment on the options very soon.

**Comment by crazyhuggins** [comment] 2016-11-29 12:25
This is funny!

With the comment there, it fail parsing for me. If I remove the comment, it works!

```js
class A {
 constructor() {
        super()  // hello, world!
}
 }
```

**Comment by crazyhuggins** [comment] 2016-11-29 13:00
@icefapper This one get parsed in my end as ExpressionStatement, but this is part of ES2017 is not implemented. So it should not be parsed at all. Instead throw an syntax error.

```js
({ async: true })
```

Plans to include ES2017?

**Comment by crazyhuggins** [comment] 2016-11-29 13:40
@icefapper And this combos I can not get working on the master branch in either strict or loose mode.

```js

export {default} from "foo";
export {foo as default} from "foo";
export {foo as bar} from "foo";
export {foo as default, bar} from "foo";
export {foo} from "foo";
export {foo, bar} from "foo";
export {foo as bar};
export {foo as default, bar};
```

**Comment by crazyhuggins** [comment] 2016-11-30 00:35
@icefapper I'm done reading and testing things out, and one thing to say: AWSOME WORK!! Congrats!

I know got a much better understanding on how things works, and I also tested things while I was reading to try to find bugs. Here is the last few combos that I couldn't get working. This is working for Acorn.

```js
({ x(...[ a, b ]){} })
function f([x] = [1]) { 'use strict' }
({ x({ a: { w, x }, b: [y, z] }, ...[a, b, c]){} })
[a, ...[b, c]] = d
var [a, ...[b, c]] = d
/[a-z]/u

(function () { yield* 10 })

Should throw syntax error according to the specs

for (let x = 42 in list) process(x);
```

I'm now ready to help you out with this module. Is there any place we could talk except for a issue tread?

I think the main task now should be to fix location and range. Agree?

However. I found numerous mistakes in your code. E.g. functions got called with more parameters then arguments.

Look at the `this.err()` function. It only take 3 arguments, but some places you actually invoke it with 5 or 6 arguments!!

This will cause bugs, because you are also checking if a error exist, and then throws if it does. However if you call this.err with for many arguments, this will always be falsy.

**Comment by crazyhuggins** [comment] 2016-11-30 10:43
@icefapper Seems to be tons of issues related to inline comments. This will not parse:

```js
42 // line comment
// Hello, world!\n42
// Hello, world!\n
//\n42
// Hallo, world!\n
// Hallo, world!\n
```

You can find more examples in Acorns own tests here: https://github.com/ternjs/acorn/blob/master/test/tests.js#L4994-L5381

**Comment by icefapper** [comment] 2016-11-30 11:29
@crazyhuggins Thanks for all the time you have put in pushing the parser to its limits :)

>  Seems to be tons of issues related to inline comments. This will not parse:
```
42 // line comment
// Hello, world!\n42
// Hello, world!\n
//\n42
// Hallo, world!\n
// Hallo, world!\n
```
Strange, this one is parsing all right for me.

@zenekron Hi there! I've recentry beel back to work on the parser -- after doing much dirty experimentation with the [vaseline branch](https://github.com/JazzleWare/jazzle-parser/tree/vaseline)

Mind you give me a hand reproducing the errors @crazyhuggins is talking about? 
I've not been able to reproduce them myself -- none of the syntactically valid cases in this issue are giving errors for me, so either I'm missing something, or something is wrong with @crazyhuggins' version of the parser. Thanks a lot in advance!

**Comment by icefapper** [comment] 2016-11-30 11:31
@crazyhuggins you are totally right about the `(2 ** -1) * 2` thing. I have not yet built the support for the `**` operator into jazzle.

Thanks a lot pointing that out though, I've just started working on it!

**Comment by crazyhuggins** [comment] 2016-11-30 12:40
@icefapper So you don't think I am joking around. Look at this:

```js
\jazzle.js:1587
  return errorMessage.replace( /%\{([^\}]*)\}/g,
                     ^

TypeError: Cannot read property 'replace' of undefined
    at createMessage (jazzle.js:1587:22)
    at Parser.err (jazzle.js:1572:27)
    at Parser.parseFunc (jazzle.js:2079:12)
```

In this case I tried this combo `if (morning) (function(){})`

Similiar errors is what I get with other comboes I mentioned.

**Comment by crazyhuggins** [comment] 2016-11-30 13:05
Okay, @icefapper  You got me hooked on this. I don't know where the errors are coming from or where. But I am now using  analyzing tools from my work, and also re-build your source code step-by-step to find all flaws. There seems to be a few.

After this process is completed, I will bundle it and try your tests. And send you a list of things to fix.

Sounds okay?

**Comment by icefapper** [comment] 2016-11-30 14:20
@crazyhuggins Thanks for taking time trudging through the dirty parts of the code -- What you are doing is, dare I say, a heroic feat. I really meant it. thanks again.

> So you don't think I am joking around. Look at this:
```js
\jazzle.js:1587
  return errorMessage.replace( /%\{([^\}]*)\}/g,
                     ^
TypeError: Cannot read property 'replace' of undefined
    at createMessage (jazzle.js:1587:22)
    at Parser.err (jazzle.js:1572:27)
    at Parser.parseFunc (jazzle.js:2079:12)
```
> In this case I tried this combo `if (morning) (function(){})`
Similiar errors is what I get with other comboes I mentioned.

You are completely right on that -- but still, mind you somehow share a "zip" of your version of jazzle npm module? This I'm asking because I've installed the latest jazzle module via npm but I've not been able to get the errors that you are getting on your machine.

As for the bugs you have listed (and I'm _so_ grateful you did), here is my ideas on some of them:
```js
(...a, ...b) => 0
// the above is indeed a syntax error -- a function can have only one rest parameter, which, if present, 
// must come at the end of the parameter list

((a)) => 0
// this is an error too -- function parameters must not be parenthesized

eval => 42
(a) => 00
// without having a semicolon after 42, the code above is actually parsed as:
eval => 42(a) => 00
// which is actually a syntax error; with semicolon in the right place though, they will parse without
// any errors when in strict mode:
eval => 42;
a => 00;
 
export {default} from "foo";
export {foo as default} from "foo";
export {foo as bar} from "foo";
export {foo as default, bar} from "foo";
export {foo} from "foo";
export {foo, bar} from "foo";
export {foo as bar};
export {foo as default, bar}; 
// all of the programs above contain an export declaration, which is a module-level source element;
// this means they must be parsed a module code, rather than as script code; so,
var Parser = require('jazzle').Parser;
var code = 'export {default} from "foo";';
new Parser(code).parseProgram(); // won't work because it parses 'code' as a script-level source
new Parser(code, true).parseProgram(); // will work, because it parses 'code' as a module-level source

class A {a(eval){}}
// the code above should not cause a syntax error. I have just tested it in jazzle but 
// I could not get any errors while parsing it.

({ x(...[ a, b ]){} })
// this is a syntax error indeed, and it actually should cause a parse error -- `...[a, b]` can not be a
//function parameter, because the argument of a BindingRestElement must be an Identifier

function f([x] = [1]) { 'use strict' }
// this is a syntax error too -- a function with a "use strict" directive 
// can only have a simple parameter list, i.e., one that is solely consisting of Identifiers

({ x({ a: { w, x }, b: [y, z] }, ...[a, b, c]){} })
// this is a syntax error too -- `...[a, b, c]` can't be a parameter to x, because `[a, b, c]` 
// is not an Identifier, which disqualifies the `...[a, b, c]` thing from being a BindingRestElement

[a, ...[b, c]] = d
var [a, ...[b, c]] = d
// same as above

/[a-z]/u
// this is actually a valid regex, and I have no idea why it's not working on your machine.

(function () { yield* 10 })
// this is not a syntax error -- except for when in strict mode, yield is an ordinary identifier when not in a
// generator's body.

for (let x = 42 in list) process(x);
// you are actually right about this -- it used to be invalid per ES2015, but looks to have creeped back // into the most recent versions of the spec, under the pretext of compatiblity or something like that
```

I hope I've clarified a number of issues there, and, once again, I would be very grateful to know your feedback!

**Comment by icefapper** [comment] 2016-11-30 14:36
@crazyhuggins 
> Look at the this.err() function. It only take 3 arguments, but some places you actually invoke it with 5 or 6 arguments!!

I confess I've not put much time in the error reporting subsystem, but I have to add that calling `this.err` with many arguments has been intentional -- I once intended to treat `err` as an arbiter, calling a relevant error routine based on the error type it has received.

Granted, your argument is pretty justified -- I guess the code is now stable enough to start working on stuff like better error reporting and tolerant parsing.

**Comment by icefapper** [comment] 2016-11-30 14:39
@crazyhuggins 
> Can you try this combination - both strict and not strict and let me know ASAP if it works for you?
```js
if (morning) function a(){}
```

Thanks a lot pointing that out. I fixed it in the master branch.

**Comment by crazyhuggins** [comment] 2016-11-30 14:42
@icefapper I re-bundled your source code on the master branch after analyzing it. And I'm now getting the same things as you do. When I tested some of the combos I was using the build in the dist folder. Wich is 2 months old! 

Now things working, but the analyze gave me a long line of red alerts. See my comments earlier today where I mentioned that you e.g. are invoking `this.err`  with too many arguments. So when you check if the error exist, and you rely on the arguments, it will be a failure (*my guess*).

In some other parts of the code - I mentioned it earlier today - you are using variabels that does not exist, or you are invoking a function that is misspelled.  I can't remember just now where it was located, but you invoked this one `errorHAndlerOutput` and it should be `errorHandlerOutput`. And another place you actually invoke `errorHandler`. No idea where that variable are coming from.

This things in your code can and will give unexpected behaviour, and maybe that is what I triggered earlier today.

A listed a few in a previous comment.

And now when I go through your code, I almost went crazy because of the `location` and `range`.

There has to be a way to turn it off!!!

So I started looking into it, and too start with you can follow this few steps

1. Change  `var Parser = function (src, isModule) { ` to this `var Parser = function (src, options) { ` 

2. Change `this.tight = !!isModule ;` into this

```js
this.tight = typeof options.sourceType === 'module' ? true : false
```

Now you have a option object. However you can remove `isScript` now, and do this instead
`!this.tight`

Then your strict / loose mode is back.

3. For range and location, do this:

```js
this.isRange  =  typeof options.range  === 'module' ? true : false
this.isLocation =  typeof options.location === 'module' ? true : false
```

Now you can do this in your code

```js
if(this.isRange) { ... }
if(this.isLocation) { ... }
```

That is how far I come with this now.

**Comment by icefapper** [comment] 2016-11-30 14:43
@crazyhuggins 
> In the constructor you have other names like
```js
v
li0
col0
c0
```
> What are they? For me they are only confusing!

the `li0`, `col0`, and `c0` member variables are the starting line, the starting column, and the starting offset of an Identifier or a Literal token.

`v` is the `version` of the ECMAScript we are going to parse against.

**Comment by crazyhuggins** [comment] 2016-11-30 14:48
I see. Maybe better variable names? And how are you setting this `v` variable or is it automatic?

Regarding location and range again. The returned object in the `parseProgram` is not valid after the `ESTree specs` because it's containing location data. And mostly the same with your other similar objects.
I was looking into `Acorn` on how to solve this, but has yet to find a good solution. Things stick too deep into the source code.

**Comment by crazyhuggins** [comment] 2016-11-30 14:52
@icefapper Could you push your latest Master branch changes so I can follow you?

**Comment by icefapper** [comment] 2016-11-30 14:53
@crazyhuggins I actually have done so :)

**Comment by icefapper** [comment] 2016-11-30 14:55
mind you join in on [the parser's channel on gitter](https://gitter.im/icefapper/jsRube?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)?

**Comment by crazyhuggins** [comment] 2016-11-30 15:16
@icefapper Which master branch and wich repo did you push to? The master branch I see was updated yesterday.

```js
Latest commit 1bbac8b  a day ago
```

I can join the channel soon. Need to solve a issue with my wife atm.

**Comment by crazyhuggins** [comment] 2016-11-30 15:20
Your friend zenekron has not been active since august. He made a new repo november 13. Else no activity.

**Comment by icefapper** [comment] 2016-11-30 15:23
@crazyhuggins Yeah :\
By the way, the push actually happened on [vaseline](https://github.com/JazzleWare/jazzle-parser/tree/vaseline)

**Comment by crazyhuggins** [comment] 2016-11-30 15:35
@icefapper I see. And I also noticed that vaseline branch is not master compatible. 

Sorry to say, but I have to go offline. In my world it's the middle of the night. 11.32 PM and I have to be up again 3 AM.

After squeezing the bugs I may have located, I think the first thing to focus on now is to fix location and range. That way you can be sure the returned elem objects are `ESTree` compatible. As they are not now.

When they are compatible, you should also concider async and await implementation as next step. This will require an extra variable to each `Estree` object - `async: boolean`.

When this is done you have 100% EStree compat and can squeeze more bugs, fix error handling etc.

Just my thoughts!

I will be back online later on and also join gitter..

**Comment by icefapper** [comment] 2016-11-30 15:40
Wish you the best, @crazyhuggins!
(Also I just pushed to the master branch.)

**Comment by crazyhuggins** [comment] 2016-11-30 22:11
@icefapper Just to clearify. What is this scope thing? Is it really needed? You almost scared me off with it, and I haven't had any time yet to read that source.

But most devs like module with less code size and with this scope you added over 2500 extra lines of code!
And your module is now  178 KB. 

My point of view is that people prefer Acorn because of it's modularity, AND it's small code size. Esprima looses popularity because it's size is now over 250  kb! And it's not modular.

My suggestion is. What about not having this scope in the core, but offer some kind of plugins like Acorn? I'm sure things can be done without 2k extra lines.

Correct me if I'm wrong. This was just my point of view.

**Comment by icefapper** [comment] 2016-12-01 08:13
@crazyhuggins Welcome back!
Are you sure about the scope subsystem bloating the final bundle by 2500 lines? I have just compared [the bundle before incorporating the scope tracker](https://github.com/JazzleWare/jazzle-parser/blob/1bbac8b44a7c63ce6f4d0ff99cae6bd6f7a86cbc/dist/jazzle.js) with the [latest bundle](https://github.com/JazzleWare/jazzle-parser/blob/master/dist/jazzle.js) -- the difference was a little less than 400 lines; and as for the size, the bundle has grown from ~169KB to about ~178KB, which is a 10KB increase.

I would be glad to know if I'm missing something.

> What about not having this scope in the core, but offer some kind of plugins like Acorn? I'm sure things can be done without 2k extra lines.

I wish it was not needed; but a number of early errors in the spec need a scope tracker in order to be caught. I have to cede though, that that scope tracker in its current state is probably tad too vigorous; my hopes are to make it more lightweight in the very near future.

**Comment by crazyhuggins** [comment] 2016-12-01 08:22
My mistake. I was comparing against the vaseline branch wich are `9692 lines (7914 sloc)  272 KB`

So how is the plans for the scope?

**Comment by crazyhuggins** [comment] 2016-12-01 08:29
@icefapper I am on gitter now. Waiting for you there

**Closed** 2016-12-30 16:30 UTC
